### PR TITLE
Add missing packages dependencies

### PR DESCRIPTION
**Pull request by jsep**
Solve #2 issue

### CODE REVIEW

**Comment by lukeclifton** [comment]
Thanks @jsep! Good spot. I must of had these packages installed in apps that i've worked on and not realised they were missing as package dependencies. Thanks for the PR!

**Comment by jsep** [comment]
You're welcome :smile:

**Comment by lukeclifton** [comment]
@jsep Have you been using this meteor-shopify-api package? Interested to get your thoughts on it if you have been? I know it still needs work and improvements.

**Comment by jsep** [comment]
Actually i'm just using the oath logic of your package, for now so far so good

**Comment by lukeclifton** [comment]
@jsep Ah great. Let me know if you see any areas for improvement.

I would like to restructure the oAuth stuff so that it follows the same structure as the official core oAuth packages. This was my first time working with oAuth and Meteor.

**Pull request merged**
